### ISSUE TITLE
WebKit does not support Amazon Music

### ISSUE THREAD

**Issue by Suzie97** [mirkobrombin/Amusiz#6] opened 2021-06-23 17:45 UTC
When I logged in with my amazon account, amazon displayed me a message asking to download chrome or firefox.

**Comment by mirkobrombin** [comment] 2021-06-23 17:46
Are you using the AUR version?

**Comment by Suzie97** [comment] 2021-06-25 10:10
No I'm using the app image on elementary OS 6 beta 2

**Comment by mirkobrombin** [comment] 2021-06-25 10:14
The Appimage Is broken, I'm working on it. You should build with meson and install all the requiree gstream plugins.

**Comment by Suzie97** [comment] 2021-06-25 10:39
I built it from source. But the app does not run. Is it that I'm missing the gstream plugins you mentioned? If so, how do I get them?

**Comment by mirkobrombin** [comment] 2021-06-25 10:47
> I built it from source. But the app does not run. Is it that I'm missing the gstream plugins you mentioned? If so, how do I get them?

What error does it show you? Run amusiz from the terminal post the output.

**Comment by Suzie97** [comment] 2021-06-25 10:53
> > I built it from source. But the app does not run. Is it that I'm missing the gstream plugins you mentioned? If so, how do I get them?
> 
> What error does it show you? Run amusiz from the terminal post the output.

Is the file inside `build/src/amusiz` the executable?

**Comment by mirkobrombin** [comment] 2021-06-25 10:57
> > > I built it from source. But the app does not run. Is it that I'm missing the gstream plugins you mentioned? If so, how do I get them?
> > 
> > 
> > What error does it show you? Run amusiz from the terminal post the output.
> 
> Is the file inside `build/src/amusiz` the executable?

No, you have to compile Amusiz so that you have the amusiz command and the desktop entry in the menu.

```bash
git clone https://github.com/mirkobrombin/Amusiz.git
cd Amusiz
meson build
cd build
ninja
sudo ninja install
amusiz
```

**Comment by Suzie97** [comment] 2021-06-25 11:00
```
Traceback (most recent call last):
  File "/usr/bin/amusiz", line 56, in <module>
    from amusiz import main
  File "/usr/share/amusiz/amusiz/main.py", line 24, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
```

**Comment by mirkobrombin** [comment] 2021-06-25 11:36
> ```
> Traceback (most recent call last):
>   File "/usr/bin/amusiz", line 56, in <module>
>     from amusiz import main
>   File "/usr/share/amusiz/amusiz/main.py", line 24, in <module>
>     gi.require_version('WebKit2', '4.0')
>   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit2 not available
> ```

You are missing some dependencies:

    - libwebkit2gtk-4.0
    - gir1.2-gtk-3.0
    - gir1.2-handy-1
    - gir1.2-notify-0.7
    - gir1.2-webkit2-4.0
    - libgstreamer1.0-0
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-libav
    - gstreamer1.0-alsa
    - gstreamer1.0-pulseaudio

**Comment by Suzie97** [comment] 2021-06-25 12:52
Can you list these in the readme??

**Comment by mirkobrombin** [comment] 2021-06-25 13:08
> Can you list these in the readme?

https://github.com/mirkobrombin/Amusiz/commit/7610ab1f5e8e940d1b9fb1da052e59754069b6cd

**Comment by mirkobrombin** [comment] 2021-06-26 06:39
Hi, if the problem is solved, I close the issue. 
PS. There is also a new Appimage that should also works on Ubuntu based distributions.

**Comment by Suzie97** [comment] 2021-06-26 06:49
Sorry, I haven't tested it out yet, I'll notify you

**Comment by Suzie97** [comment] 2021-06-27 14:24
The .appimage still does not work, I get the log in screen once, but the app crashes when I try to input my password.

**Comment by mirkobrombin** [comment] 2021-06-27 14:27
> The .appimage still does not work, I get the log in screen once, but the app crashes when I try to input my password.

This seems a different error. Is it working building from source?

**Closed** 2021-07-08 13:59 UTC
